version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kruty_craft
    networks:
      static:
        ipv4_address: 172.20.128.2
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    networks:
      - static
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

volumes:
  pgdata:

networks:
  static:
    ipam:
      config:
        - subnet: "172.20.0.0/16"
