version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kruty_craft
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@103.196.152.93:5432/kruty_craft?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "103.196.152.93:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]