name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ijull/go-htmx:v1 .
          docker push ijull/go-htmx:v1

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf go-htmx

            sudo docker stop go-htmx-api-1
            sudo docker rm go-htmx-api-1

            sudo docker stop go-htmx-postgres-1
            sudo docker rm go-htmx-postgres-1

            sudo docker rmi go-htmx-api

            sudo git clone https://github.com/IJ4L/go-htmx
            cd go-htmx
            sudo docker-compose up -d
            sudo docker ps -a
